from colorama import Fore, Style

RESET = Style.RESET_ALL

# Bright Styles
BRIGHT_GREEN   = RESET + Style.BRIGHT + Fore.GREEN
BRIGHT_RED     = RESET + Style.BRIGHT + Fore.RED
BRIGHT_YELLOW  = RESET + Style.BRIGHT + Fore.YELLOW
BRIGHT_BLUE    = RESET + Style.BRIGHT + Fore.BLUE
BRIGHT_CYAN    = RESET + Style.BRIGHT + Fore.CYAN
BRIGHT_MAGENTA = RESET + Style.BRIGHT + Fore.MAGENTA
BRIGHT_WHITE   = RESET + Style.BRIGHT + Fore.WHITE

# Dim Styles
DIM_GREEN   = RESET + Style.DIM + Fore.GREEN
DIM_RED     = RESET + Style.DIM + Fore.RED
DIM_YELLOW  = RESET + Style.DIM + Fore.YELLOW
DIM_BLUE    = RESET + Style.DIM + Fore.BLUE
DIM_CYAN    = RESET + Style.DIM + Fore.CYAN
DIM_MAGENTA = RESET + Style.DIM + Fore.MAGENTA
DIM_WHITE   = RESET + Style.DIM + Fore.WHITE

# Normal Styles
NORMAL_GREEN   = RESET + Style.NORMAL + Fore.GREEN
NORMAL_RED     = RESET + Style.NORMAL + Fore.RED
NORMAL_YELLOW  = RESET + Style.NORMAL + Fore.YELLOW
NORMAL_BLUE    = RESET + Style.NORMAL + Fore.BLUE
NORMAL_CYAN    = RESET + Style.NORMAL + Fore.CYAN
NORMAL_MAGENTA = RESET + Style.NORMAL + Fore.MAGENTA
NORMAL_WHITE   = RESET + Style.NORMAL + Fore.WHITE
